#!/bin/bash
sudo apt update && sudo apt upgradre -y
sudo apt-get install lib32gcc-s1 -y
sudo apt-get install unzip -y
path=$(pwd)
mkdir -p .steamcmd
mkdir -p gmodserver
cd .steamcmd
wget "https://steamcdn-a.akamaihd.net/client/installer/steamcmd_linux.tar.gz"
tar -xvzf steamcmd_linux.tar.gz
rm steamcmd_linux.tar.gz
./steamcmd.sh +force_install_dir "$path/gmodserver" +login anonymous +app_update 232330 validate +app_update 4020 validate +quit
cd ..
cd gmodserver/garrysmod/cfg
rm mount.cfg
cat <<EOF > mount.cfg
"mountcfg"
{
"cstrike"	"$path/gmodserver/cstrike"
}
EOF
sudo chmod 775 mount.cfg
cd ..
cd gamemodes
wget "https://github.com/FPtje/DarkRP/archive/refs/heads/master.zip"
unzip master.zip
rm master.zip
mv DarkRP-master darkrp
cd ..
mkdir -p addons
cd addons
wget "https://github.com/FPtje/darkrpmodification/archive/refs/heads/master.zip"
unzip master.zip
rm master.zip
mv darkrpmodification-master darkrpmodification
wget "https://github.com/TeamUlysses/ulib/archive/refs/heads/master.zip"
unzip master.zip
rm master.zip
mv ulib-master ulib
wget "https://github.com/TeamUlysses/ulx/archive/refs/heads/master.zip"
unzip master.zip
rm master.zip
mv ulx-master ulx
cd "$path"
cd gmodserver
cat <<EOF > hl2_run
#!/bin/bash
./srcds_run -game garrysmod -console +gamemode darkrp +map gm_construct +sv_lan 1 +maxplayers 69 +host_workshop_collection 0 -tickrate 66 +hostname "TheSuperServer" -port 27020 +clientport 27010 +sv_password ""
EOF
sudo chmod 770 hl2_run
cd "$HOME"
rm -r Steam
